name: Claude PR Assistant

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request:
    types: [opened]

jobs:
  claude-assistant:
    # Only run if @claude is mentioned
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude')) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.body, '@claude'))
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for better context
          fetch-depth: 0

      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@main
        with:
          trigger_phrase: "@claude"
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          timeout_minutes: "25"
          max_turns: "10"
          # Custom prompt context for ADHD-OS project
          context_message: |
            You are helping with the ADHD Operating System (ADHD-OS) project.
            This is an Obsidian plugin designed specifically for users with ADHD.
            Key features include: task management, time awareness, focus tools, 
            and crisis management. Always consider ADHD-specific needs when 
            implementing features or reviewing code.