name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "src/**/*.ts"
      - "src/**/*.tsx"
      - "main.ts"
      - "manifest.json"
      - "**/*.test.ts"

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@main
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Direct prompt for ADHD-OS specific review
          direct_prompt: |
            Please review this pull request for the ADHD Operating System (ADHD-OS) Obsidian plugin.
            
            Focus on these ADHD-specific aspects:
            
            1. **Cognitive Load & Simplicity**:
               - Is the UI/UX simple and not overwhelming?
               - Are there too many options or decisions presented at once?
               - Is progressive disclosure used appropriately?
            
            2. **ADHD-Friendly Features**:
               - Clear visual feedback and indicators
               - Appropriate use of colors and contrast
               - Support for quick capture without friction
               - Time awareness considerations
               - Crisis mode support
            
            3. **Code Quality**:
               - TypeScript best practices and type safety
               - Obsidian plugin API usage
               - Performance (especially for users with many notes)
               - Memory management
               - Error handling with helpful messages
            
            4. **Accessibility**:
               - WCAG AA compliance
               - Keyboard navigation support
               - Screen reader compatibility
               - Cognitive accessibility features
               - Clear labeling and instructions
            
            5. **Testing**:
               - Are tests included for new features?
               - Do tests cover ADHD-specific scenarios?
               - Edge cases for overwhelm/crisis situations?
            
            Provide specific, actionable feedback. Be encouraging and constructive.
            Remember: This plugin helps users with ADHD manage their lives better.

          # Use sticky comments to update the same review comment
          use_sticky_comment: true
          
          # Timeout for the review
          timeout_minutes: "10"
          
          # Maximum conversation turns
          max_turns: "5"
          # Optional: Customize review based on file types
          # direct_prompt: |
          #   Review this PR focusing on:
          #   - For TypeScript files: Type safety and proper interface usage
          #   - For API endpoints: Security, input validation, and error handling
          #   - For React components: Performance, accessibility, and best practices
          #   - For tests: Coverage, edge cases, and test quality
          
          # Optional: Different prompts for different authors
          # direct_prompt: |
          #   ${{ github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR' && 
          #   'Welcome! Please review this PR from a first-time contributor. Be encouraging and provide detailed explanations for any suggestions.' ||
          #   'Please provide a thorough code review focusing on our coding standards and best practices.' }}
          
          # Optional: Add specific tools for running tests or linting
          # allowed_tools: "Bash(npm run test),Bash(npm run lint),Bash(npm run typecheck)"
          
          # Optional: Skip review for certain conditions
          # if: |
          #   !contains(github.event.pull_request.title, '[skip-review]') &&
          #   !contains(github.event.pull_request.title, '[WIP]')

