name: Task Complexity Analysis

on:
  schedule:
    - cron: '0 8 * * 1' # Every Monday at 8 AM
  workflow_dispatch:
  pull_request:
    paths:
      - '.taskmaster/tasks.json'

jobs:
  analyze-complexity:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install Task Master
      run: npm install -g task-master-ai
      
    - name: Set up API Keys
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY" >> .env
        echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
        
    - name: Run Complexity Analysis
      run: |
        task-master analyze-complexity --research --threshold=5
        
    - name: Generate Complexity Report
      run: |
        task-master complexity-report --file=.taskmaster/reports/complexity-$(date +%Y-%m-%d).md
        
    - name: Upload Analysis Report
      uses: actions/upload-artifact@v4
      with:
        name: complexity-analysis
        path: .taskmaster/reports/complexity-*.md
        
    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('.taskmaster/reports/complexity-' + new Date().toISOString().split('T')[0] + '.md', 'utf8');
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '## 📊 Task Complexity Analysis\n\n' + report
          });